# Use root/example as user/password credentials
version: '3.1'

services:
  benchmark_main:
    image: benchmark_main:latest
    restart: always
    volumes:
      #- /mnt/wsl/docker-desktop/volumes/mysql/data:/var/lib/mysql
      - /mnt/wsl/docker-desktop/volumes/mysql/mysql-files:/var/lib/mysql-files
      #- /mnt/wsl/docker-desktop/volumes/postgres/data:/var/lib/postgresql/12/main
      # - /mnt/c/docker/volumes/mysql/data:/var/lib/mysql
      # - /mnt/c/docker/volumes/mysql/mysql-files:/var/lib/mysql-files
      # - /mnt/c/docker/volumes/postgres/data:/var/lib/postgresql/12/main
    environment:
      MYSQL_ROOT_PASSWORD: 'edward'
      POSTGRES_USER: 'edward'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 3307:3306
      - 5432:5432

  # pgadmin:
  #   depends_on:
  #     - benchmark_main
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
  #     PGADMIN_DEFAULT_PASSWORD: 'edward'
  #     PGADMIN_LISTEN_PORT: 80
  #   # volumes:
  #   #   - ./data/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - 8081:80
  #   restart: always

  # adminer:
  #   depends_on:
  #     - benchmark_main
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
