# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: edward
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    ports:
      - 3307:3306

  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: edward
        POSTGRES_DB: benchmark
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config/postgres:/etc/postgresql
    ports:
      - 5432:5432

  timescale:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: edward
    volumes:
      - ./data/timescale:/var/lib/postgresql/data
      - ./config/postgres:/etc/postgresql
    ports:
      - 5433:5432
  
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'edward'
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 8081:80
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080