# Use root/example as user/password credentials
version: '3.1'

services:
  benchmark_main:
    image: benchmark_main:latest
    restart: always
    # volumes:
    #   - ./data/mysql:/var/lib/mysql
    #   - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 'edward'
      POSTGRES_PASSWORD: 'edward'
    ports:
      - 3307:3306
      - 5432:5432

  # pgadmin:
  #   depends_on:
  #     - benchmark_main
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
  #     PGADMIN_DEFAULT_PASSWORD: 'edward'
  #     PGADMIN_LISTEN_PORT: 80
  #   # volumes:
  #   #   - ./data/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - 8081:80
  #   restart: always

  # adminer:
  #   depends_on:
  #     - benchmark_main
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080