SELECT * FROM epack_Messaging.user_messages order by message_date desc;CREATE TABLE `coupon_issued` (
  `id` int(11) NOT NULL,
  `serial` bigint(20) NOT NULL,
  `secret` varchar(32) NOT NULL,
  `is_burnable` tinyint(1) NOT NULL DEFAULT '0',
  `expiration` datetime DEFAULT NULL,
  `incipience` datetime DEFAULT NULL,
  `overall_use_count` int(11) NOT NULL DEFAULT '0',
  `period_use_count` int(11) NOT NULL DEFAULT '0',
  `last_use_timestamp` datetime DEFAULT NULL,
  `last_action` varchar(20) DEFAULT NULL,
  `tracked_use_count` int(11) NOT NULL DEFAULT '0',
  `last_tracked_timestamp` datetime DEFAULT NULL,
  `tracked_active_until` datetime DEFAULT NULL,
  `available_redemptions` int(11) DEFAULT '0',
  `last_redemption_earned` datetime DEFAULT NULL,
  `last_number_of_redemptions_applied` int(11) DEFAULT '0',
  `number_of_redemptions_earned_in_time_period` int(11) DEFAULT '0',
  `last_apply_amount` decimal(9,2) DEFAULT NULL,
  `registration_timestamp` datetime DEFAULT NULL,
  `user_reference_id` varchar(100) DEFAULT NULL,
  `is_deactivated` tinyint(1) DEFAULT '0',
  `has_received_registration_reward` tinyint(1) DEFAULT '0',
  `campaign_id` int(11) DEFAULT NULL,
  `coupon_short_id` varchar(25) DEFAULT NULL,
  `coupon_barcode` varchar(100) DEFAULT NULL,
  `first_transaction_timestamp` datetime DEFAULT NULL,
  PRIMARY KEY (`id`,`serial`),
  UNIQUE KEY `short_id_INDEX` (`coupon_short_id`),
  KEY `user_reference_id_INDEX` (`user_reference_id`),
  KEY `barcode_INDEX` (`coupon_barcode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
